### ISSUE TITLE
Curious about roadmap

### ISSUE THREAD

**Issue by andrewhavens** [efreesen/active_repository#10]
Just came across your project while looking for a gem that supports database agnostic persistence. I need to find something that supports both SQL and No-SQL data stores. Looks like your gem has a nice start on this. I think the repository pattern is a nice solution for this problem. However, it looks like your gem requires you to write models for each database/ORM that you want to support. What are your plans for this gem? Do you have any plans to make it so you can write models which aren't tied to an ORM (so you can write the model once)?

**Comment by efreesen** [comment]
Hi @andrewhavens,

Glad you like my work. Lately I have had no time to work on this gem, but this gem have kind of a misconcept. The Repository Pattern says the repository should not know nothing about persistence, and this gem, knows a lot about it. I need to separate this gem into at least 2 other gems, one for the repository, which does not know nothing about persistence, and the other gem, an ORM that uses adapters to connect to the database.

With the last one you could write one "model" and point it to the database you want. But it is far from becoming reality as I became a father and time is a precious resource for me now :smiley: 

Thank you for your interest.

**Comment by andrewhavens** [comment]
Hi @efreesen,

Thanks for the reply and for the insight on your direction/availability. I know how you feel! I also have two young kids. I also agree about your understanding of the repository pattern. I came across [Curator](https://github.com/braintree/curator) which seems to already support the API I was hoping for. I'm curious if you've seen it and what you think of it.

**Comment by efreesen** [comment]
Hey Thank you for pointing the Curator gem. I didn't know it, I think it is somehow still coupled to the database, but it is a good start. It is great to see so much gems and people from the community working with DDD.

Thank you for the information, see ya.

**Comment by kirantpatil** [comment]
How about  https://github.com/hanami/model (A persistence framework with entities, repositories, data mapper and query objects ) ?

**Comment by efreesen** [comment]
Hi @kirantpatil, I have followed Lotus for a while now (yet to check its new form: Hanami), and I think it is a great framework. But IMHO their persistence layer is much more complex than it could be.

In my blog http://efreesen.com I am trying to show a simpler approach, using POROs and some small gems to help you decouple your logic and achieve framework independence.

Thank you for your interest.
